local texturesimg = {
  {
    "[Realistic-Effects]/img/afterburner.png",
    "afterburner"
  },
  {
    "[Realistic-Effects]/img/ashes.png",
    "ashes"
  },
  {
    "[Realistic-Effects]/img/ashes2.png",
    "ashes2"
  },
  {
    "[Realistic-Effects]/img/beam.png",
    "beam"
  },
  {
    "[Realistic-Effects]/img/beamcorona.png",
    "beamcorona"
  },
  {
    "[Realistic-Effects]/img/beastie.png",
    "beastie"
  },
  {
    "[Realistic-Effects]/img/Bgush1.png",
    "Bgush1"
  },
  {
    "[Realistic-Effects]/img/Bgush2.png",
    "Bgush2"
  },
  {
    "[Realistic-Effects]/img/Bgush3.png",
    "Bgush3"
  },
  {
    "[Realistic-Effects]/img/Bgush4.png",
    "Bgush4"
  },
  {
    "[Realistic-Effects]/img/blaze1.png",
    "blaze1"
  },
  {
    "[Realistic-Effects]/img/blaze2.png",
    "blaze2"
  },
  {
    "[Realistic-Effects]/img/blaze3.png",
    "blaze3"
  },
  {
    "[Realistic-Effects]/img/blaze4.png",
    "blaze4"
  },
  {
    "[Realistic-Effects]/img/blood1.png",
    "blood1"
  },
  {
    "[Realistic-Effects]/img/blood2.png",
    "blood2"
  },
  {
    "[Realistic-Effects]/img/blood3.png",
    "blood3"
  },
  {
    "[Realistic-Effects]/img/blood4.png",
    "blood4"
  },
  {
    "[Realistic-Effects]/img/BloodCloud.png",
    "BloodCloud"
  },
  {
    "[Realistic-Effects]/img/blooddrop1.png",
    "blooddrop1"
  },
  {
    "[Realistic-Effects]/img/blooddrop2.png",
    "blooddrop2"
  },
  {
    "[Realistic-Effects]/img/blooddrop3.png",
    "blooddrop3"
  },
  {
    "[Realistic-Effects]/img/blooddrop4.png",
    "blooddrop4"
  },
  {
    "[Realistic-Effects]/img/BloodRayne.png",
    "BloodRayne"
  },
  {
    "[Realistic-Effects]/img/BloodSplash.png",
    "BloodSplash"
  },
  {
    "[Realistic-Effects]/img/Bnitro.png",
    "Bnitro"
  },
  {
    "[Realistic-Effects]/img/boatsplash.png",
    "boatsplash"
  },
  {
    "[Realistic-Effects]/img/boatwake1.png",
    "boatwake1"
  },
  {
    "[Realistic-Effects]/img/bsplat1.png",
    "bsplat1"
  },
  {
    "[Realistic-Effects]/img/bsplat2.png",
    "bsplat2"
  },
  {
    "[Realistic-Effects]/img/bsplat3.png",
    "bsplat3"
  },
  {
    "[Realistic-Effects]/img/bsplat4.png",
    "bsplat4"
  },
  {
    "[Realistic-Effects]/img/bsplat5.png",
    "bsplat5"
  },
  {
    "[Realistic-Effects]/img/bubbles.png",
    "bubbles"
  },
  {
    "[Realistic-Effects]/img/bullethitsmoke.png",
    "bullethitsmoke"
  },
  {
    "[Realistic-Effects]/img/bullethitsmoke1.png",
    "bullethitsmoke1"
  },
  {
    "[Realistic-Effects]/img/burn1.png",
    "burn1"
  },
  {
    "[Realistic-Effects]/img/burn2.png",
    "burn2"
  },
  {
    "[Realistic-Effects]/img/burn3.png",
    "burn3"
  },
  {
    "[Realistic-Effects]/img/burn4.png",
    "burn4"
  },
  {
    "[Realistic-Effects]/img/butterfly1.png",
    "butterfly1"
  },
  {
    "[Realistic-Effects]/img/butterfly2.png",
    "butterfly2"
  },
  {
    "[Realistic-Effects]/img/butterfly3.png",
    "butterfly3"
  },
  {"[Realistic-Effects]/img/By.png", "By"},
  {
    "[Realistic-Effects]/img/cardebris1.png",
    "cardebris1"
  },
  {
    "[Realistic-Effects]/img/cardebris2.png",
    "cardebris2"
  },
  {
    "[Realistic-Effects]/img/cardebris3.png",
    "cardebris3"
  },
  {
    "[Realistic-Effects]/img/cardebris4.png",
    "cardebris4"
  },
  {
    "[Realistic-Effects]/img/cardebris5.png",
    "cardebris5"
  },
  {
    "[Realistic-Effects]/img/cardebris_01.png",
    "cardebris_01"
  },
  {
    "[Realistic-Effects]/img/cardebris_02.png",
    "cardebris_02"
  },
  {
    "[Realistic-Effects]/img/cardebris_03.png",
    "cardebris_03"
  },
  {
    "[Realistic-Effects]/img/cardebris_04.png",
    "cardebris_04"
  },
  {
    "[Realistic-Effects]/img/cardebris_05.png",
    "cardebris_05"
  },
  {
    "[Realistic-Effects]/img/carsplash_02.png",
    "carsplash_02"
  },
  {
    "[Realistic-Effects]/img/cement.png",
    "cement"
  },
  {
    "[Realistic-Effects]/img/cigsmoke1.png",
    "cigsmoke1"
  },
  {
    "[Realistic-Effects]/img/cigsmoke2.png",
    "cigsmoke2"
  },
  {
    "[Realistic-Effects]/img/cigsmoke3.png",
    "cigsmoke3"
  },
  {
    "[Realistic-Effects]/img/cigsmoke4.png",
    "cigsmoke4"
  },
  {
    "[Realistic-Effects]/img/cigsmoke5.png",
    "cigsmoke5"
  },
  {
    "[Realistic-Effects]/img/cloudmasked.png",
    "cloudmasked"
  },
  {
    "[Realistic-Effects]/img/collisionsmoke.png",
    "collisionsmoke"
  },
  {
    "[Realistic-Effects]/img/coronaringa.png",
    "coronaringa"
  },
  {
    "[Realistic-Effects]/img/Debris1.png",
    "Debris1"
  },
  {
    "[Realistic-Effects]/img/Debris2.png",
    "Debris2"
  },
  {
    "[Realistic-Effects]/img/Debris3.png",
    "Debris3"
  },
  {
    "[Realistic-Effects]/img/DebrisGaEX.png",
    "DebrisGaEX"
  },
  {
    "[Realistic-Effects]/img/dirt1.png",
    "dirt1"
  },
  {
    "[Realistic-Effects]/img/dirt2.png",
    "dirt2"
  },
  {
    "[Realistic-Effects]/img/dragon.png",
    "dragon"
  },
  {
    "[Realistic-Effects]/img/drift1.png",
    "drift1"
  },
  {
    "[Realistic-Effects]/img/drift2.png",
    "drift2"
  },
  {
    "[Realistic-Effects]/img/drift3.png",
    "drift3"
  },
  {
    "[Realistic-Effects]/img/drift4.png",
    "drift4"
  },
  {
    "[Realistic-Effects]/img/driftb1.png",
    "driftb1"
  },
  {
    "[Realistic-Effects]/img/driftb2.png",
    "driftb2"
  },
  {
    "[Realistic-Effects]/img/driftb3.png",
    "driftb3"
  },
  {
    "[Realistic-Effects]/img/driftb4.png",
    "driftb4"
  },
  {
    "[Realistic-Effects]/img/Drop1.png",
    "Drop1"
  },
  {
    "[Realistic-Effects]/img/Drop2.png",
    "Drop2"
  },
  {
    "[Realistic-Effects]/img/dsmoke1.png",
    "dsmoke1"
  },
  {
    "[Realistic-Effects]/img/dsmoke2.png",
    "dsmoke2"
  },
  {
    "[Realistic-Effects]/img/dsmoke3.png",
    "dsmoke3"
  },
  {
    "[Realistic-Effects]/img/dsmoke4.png",
    "dsmoke4"
  },
  {
    "[Realistic-Effects]/img/electric1.png",
    "electric1"
  },
  {
    "[Realistic-Effects]/img/electric2.png",
    "electric2"
  },
  {
    "[Realistic-Effects]/img/electric3.png",
    "electric3"
  },
  {
    "[Realistic-Effects]/img/electric4.png",
    "electric4"
  },
  {
    "[Realistic-Effects]/img/electric5.png",
    "electric5"
  },
  {
    "[Realistic-Effects]/img/electric6.png",
    "electric6"
  },
  {
    "[Realistic-Effects]/img/electric7.png",
    "electric7"
  },
  {
    "[Realistic-Effects]/img/electric8.png",
    "electric8"
  },
  {
    "[Realistic-Effects]/img/Fdebris1.png",
    "Fdebris1"
  },
  {
    "[Realistic-Effects]/img/Fdebris2.png",
    "Fdebris2"
  },
  {
    "[Realistic-Effects]/img/Fdebris3.png",
    "Fdebris3"
  },
  {
    "[Realistic-Effects]/img/Fdebris4.png",
    "Fdebris4"
  },
  {
    "[Realistic-Effects]/img/feather.png",
    "feather"
  },
  {
    "[Realistic-Effects]/img/fireball1.png",
    "fireball1"
  },
  {
    "[Realistic-Effects]/img/fireball10.png",
    "fireball10"
  },
  {
    "[Realistic-Effects]/img/fireball2.png",
    "fireball2"
  },
  {
    "[Realistic-Effects]/img/fireball3.png",
    "fireball3"
  },
  {
    "[Realistic-Effects]/img/fireball4.png",
    "fireball4"
  },
  {
    "[Realistic-Effects]/img/fireball5.png",
    "fireball5"
  },
  {
    "[Realistic-Effects]/img/fireball6.png",
    "fireball6"
  },
  {
    "[Realistic-Effects]/img/fireball7.png",
    "fireball7"
  },
  {
    "[Realistic-Effects]/img/fireball8.png",
    "fireball8"
  },
  {
    "[Realistic-Effects]/img/fireball9.png",
    "fireball9"
  },
  {
    "[Realistic-Effects]/img/FireEX.png",
    "FireEX"
  },
  {
    "[Realistic-Effects]/img/FireFlame.png",
    "FireFlame"
  },
  {
    "[Realistic-Effects]/img/FireFlame3.png",
    "FireFlame3"
  },
  {
    "[Realistic-Effects]/img/flake1.png",
    "flake1"
  },
  {
    "[Realistic-Effects]/img/flake2.png",
    "flake2"
  },
  {
    "[Realistic-Effects]/img/flame1.png",
    "flame1"
  },
  {
    "[Realistic-Effects]/img/flame2.png",
    "flame2"
  },
  {
    "[Realistic-Effects]/img/flame3.png",
    "flame3"
  },
  {
    "[Realistic-Effects]/img/flame4.png",
    "flame4"
  },
  {
    "[Realistic-Effects]/img/flamethrower.png",
    "flamethrower"
  },
  {
    "[Realistic-Effects]/img/flash1.png",
    "flash1"
  },
  {
    "[Realistic-Effects]/img/flash2.png",
    "flash2"
  },
  {
    "[Realistic-Effects]/img/flash3.png",
    "flash3"
  },
  {
    "[Realistic-Effects]/img/flash4.png",
    "flash4"
  },
  {
    "[Realistic-Effects]/img/fly1.png",
    "fly1"
  },
  {
    "[Realistic-Effects]/img/fly2.png",
    "fly2"
  },
  {
    "[Realistic-Effects]/img/fly3.png",
    "fly3"
  },
  {
    "[Realistic-Effects]/img/Fnitro.png",
    "Fnitro"
  },
  {
    "[Realistic-Effects]/img/Foliage.png",
    "Foliage"
  },
  {
    "[Realistic-Effects]/img/Function-X-.png",
    "Function-X-"
  },
  {
    "[Realistic-Effects]/img/gameleaf01_64.png",
    "gameleaf01_64"
  },
  {
    "[Realistic-Effects]/img/gensplash.png",
    "gensplash"
  },
  {
    "[Realistic-Effects]/img/glassmall.png",
    "glassmall"
  },
  {
    "[Realistic-Effects]/img/glowlight.png",
    "glowlight"
  },
  {
    "[Realistic-Effects]/img/gore1.png",
    "gore1"
  },
  {
    "[Realistic-Effects]/img/gore2.png",
    "gore2"
  },
  {
    "[Realistic-Effects]/img/gore3.png",
    "gore3"
  },
  {
    "[Realistic-Effects]/img/gore4.png",
    "gore4"
  },
  {
    "[Realistic-Effects]/img/gum.png",
    "gum"
  },
  {
    "[Realistic-Effects]/img/GunFlash.png",
    "GunFlash"
  },
  {
    "[Realistic-Effects]/img/GunFlash1.png",
    "GunFlash1"
  },
  {
    "[Realistic-Effects]/img/GunFlash2.png",
    "GunFlash2"
  },
  {
    "[Realistic-Effects]/img/GunFlash3.png",
    "GunFlash3"
  },
  {
    "[Realistic-Effects]/img/GunFlash4.png",
    "GunFlash4"
  },
  {
    "[Realistic-Effects]/img/gunshell.png",
    "gunshell"
  },
  {
    "[Realistic-Effects]/img/gunsmoke.png",
    "gunsmoke"
  },
  {
    "[Realistic-Effects]/img/headshot1.png",
    "headshot1"
  },
  {
    "[Realistic-Effects]/img/headshot2.png",
    "headshot2"
  },
  {
    "[Realistic-Effects]/img/headshot3.png",
    "headshot3"
  },
  {
    "[Realistic-Effects]/img/headshot4.png",
    "headshot4"
  },
  {
    "[Realistic-Effects]/img/headshot5.png",
    "headshot5"
  },
  {
    "[Realistic-Effects]/img/inferno1.png",
    "inferno1"
  },
  {
    "[Realistic-Effects]/img/inferno2.png",
    "inferno2"
  },
  {
    "[Realistic-Effects]/img/inferno3.png",
    "inferno3"
  },
  {
    "[Realistic-Effects]/img/inferno4.png",
    "inferno4"
  },
  {
    "[Realistic-Effects]/img/inferno5.png",
    "inferno5"
  },
  {
    "[Realistic-Effects]/img/inflame1.png",
    "inflame1"
  },
  {
    "[Realistic-Effects]/img/inflame2.png",
    "inflame2"
  },
  {
    "[Realistic-Effects]/img/inflame3.png",
    "inflame3"
  },
  {
    "[Realistic-Effects]/img/inflame4.png",
    "inflame4"
  },
  {
    "[Realistic-Effects]/img/inflamed1.png",
    "inflamed1"
  },
  {
    "[Realistic-Effects]/img/inflamed2.png",
    "inflamed2"
  },
  {
    "[Realistic-Effects]/img/inflamed3.png",
    "inflamed3"
  },
  {
    "[Realistic-Effects]/img/inflamed4.png",
    "inflamed4"
  },
  {
    "[Realistic-Effects]/img/laser.png",
    "laser"
  },
  {
    "[Realistic-Effects]/img/leaf1.png",
    "leaf1"
  },
  {
    "[Realistic-Effects]/img/leaf2.png",
    "leaf2"
  },
  {
    "[Realistic-Effects]/img/light1.png",
    "light1"
  },
  {
    "[Realistic-Effects]/img/light2.png",
    "light2"
  },
  {
    "[Realistic-Effects]/img/light3.png",
    "light3"
  },
  {
    "[Realistic-Effects]/img/light4.png",
    "light4"
  },
  {
    "[Realistic-Effects]/img/light5.png",
    "light5"
  },
  {
    "[Realistic-Effects]/img/light6.png",
    "light6"
  },
  {
    "[Realistic-Effects]/img/lightning1.png",
    "lightning1"
  },
  {
    "[Realistic-Effects]/img/lightning2.png",
    "lightning2"
  },
  {
    "[Realistic-Effects]/img/lightning3.png",
    "lightning3"
  },
  {
    "[Realistic-Effects]/img/lightning4.png",
    "lightning4"
  },
  {
    "[Realistic-Effects]/img/lightning5.png",
    "lightning5"
  },
  {
    "[Realistic-Effects]/img/molotov1.png",
    "molotov1"
  },
  {
    "[Realistic-Effects]/img/molotov2.png",
    "molotov2"
  },
  {
    "[Realistic-Effects]/img/molotov3.png",
    "molotov3"
  },
  {
    "[Realistic-Effects]/img/molotov4.png",
    "molotov4"
  },
  {
    "[Realistic-Effects]/img/muzzle1.png",
    "muzzle1"
  },
  {
    "[Realistic-Effects]/img/muzzle2.png",
    "muzzle2"
  },
  {
    "[Realistic-Effects]/img/muzzle3.png",
    "muzzle3"
  },
  {
    "[Realistic-Effects]/img/muzzle4.png",
    "muzzle4"
  },
  {
    "[Realistic-Effects]/img/neon.png",
    "neon"
  },
  {
    "[Realistic-Effects]/img/NewFx1.png",
    "NewFx1"
  },
  {
    "[Realistic-Effects]/img/NewFx2.png",
    "NewFx2"
  },
  {
    "[Realistic-Effects]/img/NewFx3.png",
    "NewFx3"
  },
  {
    "[Realistic-Effects]/img/newspaper.png",
    "newspaper"
  },
  {
    "[Realistic-Effects]/img/Overdoseeffects.png",
    "Overdoseeffects"
  },
  {
    "[Realistic-Effects]/img/paper1.png",
    "paper1"
  },
  {
    "[Realistic-Effects]/img/paper2.png",
    "paper2"
  },
  {
    "[Realistic-Effects]/img/paper3.png",
    "paper3"
  },
  {
    "[Realistic-Effects]/img/paper4.png",
    "paper4"
  },
  {
    "[Realistic-Effects]/img/Pnitro.png",
    "Pnitro"
  },
  {
    "[Realistic-Effects]/img/pointlight.png",
    "pointlight"
  },
  {
    "[Realistic-Effects]/img/puke.png",
    "puke"
  },
  {
    "[Realistic-Effects]/img/railex.png",
    "railex"
  },
  {
    "[Realistic-Effects]/img/rain1.png",
    "rain1"
  },
  {
    "[Realistic-Effects]/img/rain2.png",
    "rain2"
  },
  {
    "[Realistic-Effects]/img/rain3.png",
    "rain3"
  },
  {
    "[Realistic-Effects]/img/rain4.png",
    "rain4"
  },
  {
    "[Realistic-Effects]/img/realex1.png",
    "realex1"
  },
  {
    "[Realistic-Effects]/img/realex2.png",
    "realex2"
  },
  {
    "[Realistic-Effects]/img/realex3.png",
    "realex3"
  },
  {
    "[Realistic-Effects]/img/realex4.png",
    "realex4"
  },
  {
    "[Realistic-Effects]/img/realexb1.png",
    "realexb1"
  },
  {
    "[Realistic-Effects]/img/realexb2.png",
    "realexb2"
  },
  {
    "[Realistic-Effects]/img/realexb3.png",
    "realexb3"
  },
  {
    "[Realistic-Effects]/img/realexb4.png",
    "realexb4"
  },
  {
    "[Realistic-Effects]/img/realfire1.png",
    "realfire1"
  },
  {
    "[Realistic-Effects]/img/realfire2.png",
    "realfire2"
  },
  {
    "[Realistic-Effects]/img/realfire3.png",
    "realfire3"
  },
  {
    "[Realistic-Effects]/img/realfire4.png",
    "realfire4"
  },
  {
    "[Realistic-Effects]/img/rope1.png",
    "rope1"
  },
  {
    "[Realistic-Effects]/img/rope2.png",
    "rope2"
  },
  {
    "[Realistic-Effects]/img/sewersmoke.png",
    "sewersmoke"
  },
  {
    "[Realistic-Effects]/img/smoke.png",
    "smoke"
  },
  {
    "[Realistic-Effects]/img/smoke1.png",
    "smoke1"
  },
  {
    "[Realistic-Effects]/img/smoke10.png",
    "smoke10"
  },
  {
    "[Realistic-Effects]/img/smoke11.png",
    "smoke11"
  },
  {
    "[Realistic-Effects]/img/smoke12.png",
    "smoke12"
  },
  {
    "[Realistic-Effects]/img/smoke13.png",
    "smoke13"
  },
  {
    "[Realistic-Effects]/img/smoke14.png",
    "smoke14"
  },
  {
    "[Realistic-Effects]/img/smoke2.png",
    "smoke2"
  },
  {
    "[Realistic-Effects]/img/smoke3.png",
    "smoke3"
  },
  {
    "[Realistic-Effects]/img/smoke4.png",
    "smoke4"
  },
  {
    "[Realistic-Effects]/img/smoke5.png",
    "smoke5"
  },
  {
    "[Realistic-Effects]/img/smoke6.png",
    "smoke6"
  },
  {
    "[Realistic-Effects]/img/smoke7.png",
    "smoke7"
  },
  {
    "[Realistic-Effects]/img/smoke8.png",
    "smoke8"
  },
  {
    "[Realistic-Effects]/img/smoke9.png",
    "smoke9"
  },
  {
    "[Realistic-Effects]/img/SmokeBlast.png",
    "SmokeBlast"
  },
  {
    "[Realistic-Effects]/img/SmokeBlast2.png",
    "SmokeBlast2"
  },
  {
    "[Realistic-Effects]/img/SmokeBlast3.png",
    "SmokeBlast3"
  },
  {
    "[Realistic-Effects]/img/smoked1.png",
    "smoked1"
  },
  {
    "[Realistic-Effects]/img/smoked2.png",
    "smoked2"
  },
  {
    "[Realistic-Effects]/img/smoked3.png",
    "smoked3"
  },
  {
    "[Realistic-Effects]/img/smoked4.png",
    "smoked4"
  },
  {
    "[Realistic-Effects]/img/SmokeEX.png",
    "SmokeEX"
  },
  {
    "[Realistic-Effects]/img/SmokeEX2.png",
    "SmokeEX2"
  },
  {
    "[Realistic-Effects]/img/SmokeEX3.png",
    "SmokeEX3"
  },
  {
    "[Realistic-Effects]/img/SmokeEX4.png",
    "SmokeEX4"
  },
  {
    "[Realistic-Effects]/img/SmokeEX5.png",
    "SmokeEX5"
  },
  {
    "[Realistic-Effects]/img/SmokeEX6.png",
    "SmokeEX6"
  },
  {
    "[Realistic-Effects]/img/SmokeEX7.png",
    "SmokeEX7"
  },
  {
    "[Realistic-Effects]/img/SmokeEX8.png",
    "SmokeEX8"
  },
  {
    "[Realistic-Effects]/img/SmokeEX9.png",
    "SmokeEX9"
  },
  {
    "[Realistic-Effects]/img/SmokeEXPand.png",
    "SmokeEXPand"
  },
  {
    "[Realistic-Effects]/img/smokeII_3.png",
    "smokeII_3"
  },
  {
    "[Realistic-Effects]/img/SmokeSand.png",
    "SmokeSand"
  },
  {
    "[Realistic-Effects]/img/SmokeSand2.png",
    "SmokeSand2"
  },
  {
    "[Realistic-Effects]/img/Smokethrower.png",
    "Smokethrower"
  },
  {
    "[Realistic-Effects]/img/snow1.png",
    "snow1"
  },
  {
    "[Realistic-Effects]/img/snow2.png",
    "snow2"
  },
  {
    "[Realistic-Effects]/img/snow3.png",
    "snow3"
  },
  {
    "[Realistic-Effects]/img/sonic1.png",
    "sonic1"
  },
  {
    "[Realistic-Effects]/img/sonic2.png",
    "sonic2"
  },
  {
    "[Realistic-Effects]/img/sparkdebris1.png",
    "sparkdebris1"
  },
  {
    "[Realistic-Effects]/img/sparkdebris2.png",
    "sparkdebris2"
  },
  {
    "[Realistic-Effects]/img/sparkdebris3.png",
    "sparkdebris3"
  },
  {
    "[Realistic-Effects]/img/sparkdebris4.png",
    "sparkdebris4"
  },
  {
    "[Realistic-Effects]/img/Sparks.png",
    "Sparks"
  },
  {
    "[Realistic-Effects]/img/Sparks2.png",
    "Sparks2"
  },
  {
    "[Realistic-Effects]/img/Sparks3.png",
    "Sparks3"
  },
  {
    "[Realistic-Effects]/img/Sparks4.png",
    "Sparks4"
  },
  {
    "[Realistic-Effects]/img/Sparks5.png",
    "Sparks5"
  },
  {
    "[Realistic-Effects]/img/Sparks6.png",
    "Sparks6"
  },
  {
    "[Realistic-Effects]/img/Sparks7.png",
    "Sparks7"
  },
  {
    "[Realistic-Effects]/img/SparksFlash.png",
    "SparksFlash"
  },
  {
    "[Realistic-Effects]/img/sphere.png",
    "sphere"
  },
  {
    "[Realistic-Effects]/img/sphere_CJ.png",
    "sphere_CJ"
  },
  {
    "[Realistic-Effects]/img/splash1.png",
    "splash1"
  },
  {
    "[Realistic-Effects]/img/splash2.png",
    "splash2"
  },
  {
    "[Realistic-Effects]/img/splash3.png",
    "splash3"
  },
  {
    "[Realistic-Effects]/img/splash4.png",
    "splash4"
  },
  {
    "[Realistic-Effects]/img/splash5.png",
    "splash5"
  },
  {
    "[Realistic-Effects]/img/splash6.png",
    "splash6"
  },
  {
    "[Realistic-Effects]/img/splash_up.png",
    "splash_up"
  },
  {
    "[Realistic-Effects]/img/splash_up1.png",
    "splash_up1"
  },
  {
    "[Realistic-Effects]/img/splash_up2.png",
    "splash_up2"
  },
  {
    "[Realistic-Effects]/img/splatter1.png",
    "splatter1"
  },
  {
    "[Realistic-Effects]/img/splatter2.png",
    "splatter2"
  },
  {
    "[Realistic-Effects]/img/splatter3.png",
    "splatter3"
  },
  {
    "[Realistic-Effects]/img/splatter4.png",
    "splatter4"
  },
  {
    "[Realistic-Effects]/img/water1.png",
    "water1"
  },
  {
    "[Realistic-Effects]/img/water2.png",
    "water2"
  },
  {
    "[Realistic-Effects]/img/water3.png",
    "water3"
  },
  {
    "[Realistic-Effects]/img/water4.png",
    "water4"
  },
  {
    "[Realistic-Effects]/img/waterripple1.png",
    "waterripple1"
  },
  {
    "[Realistic-Effects]/img/waterripple2.png",
    "waterripple2"
  },
  {
    "[Realistic-Effects]/img/waterripple3.png",
    "waterripple3"
  },
  {
    "[Realistic-Effects]/img/waterripple4.png",
    "waterripple4"
  },
  {
    "[Realistic-Effects]/img/waterspark.png",
    "waterspark"
  },
  {
    "[Realistic-Effects]/img/waterspark_16.png",
    "waterspark_16"
  },
  {
    "[Realistic-Effects]/img/wgush1.png",
    "wgush1"
  },
  {
    "[Realistic-Effects]/img/wjet2.png",
    "wjet2"
  },
  {
    "[Realistic-Effects]/img/wjet4.png",
    "wjet4"
  },
  {
    "[Realistic-Effects]/img/wjet6.png",
    "wjet6"
  },
  {
    "[Realistic-Effects]/img/wood1.png",
    "wood1"
  },
  {
    "[Realistic-Effects]/img/wood2.png",
    "wood2"
  },
  {
    "[Realistic-Effects]/img/wood3.png",
    "wood3"
  },
  {
    "[Realistic-Effects]/img/wood4.png",
    "wood4"
  },
  {
    "[Realistic-Effects]/img/fx2/bloodpool_64.png",
    "bloodpool_64"
  },
  {
    "[Realistic-Effects]/img/fx2/carfx1.png",
    "carfx1"
  },
  {
    "[Realistic-Effects]/img/fx2/cloud1.png",
    "cloud1"
  },
  {
    "[Realistic-Effects]/img/fx2/cloudhigh.png",
    "cloudhigh"
  },
  {
    "[Realistic-Effects]/img/fx2/cloudmasked.png",
    "cloudmasked"
  },
  {
    "[Realistic-Effects]/img/fx2/coronaheadlightline.png",
    "coronaheadlightline"
  },
  {
    "[Realistic-Effects]/img/fx2/coronamoon.png",
    "coronamoon"
  },
  {
    "[Realistic-Effects]/img/fx2/coronareflect.png",
    "coronareflect"
  },
  {
    "[Realistic-Effects]/img/fx2/coronaringb.png",
    "coronaringb"
  },
  {
    "[Realistic-Effects]/img/fx2/coronastar.png",
    "coronastar"
  },
  {
    "[Realistic-Effects]/img/fx2/finishFlag.png",
    "finishFlag"
  },
  {
    "[Realistic-Effects]/img/fx2/handman.png",
    "handman"
  },
  {
    "[Realistic-Effects]/img/fx2/headlight.png",
    "headlight"
  },
  {
    "[Realistic-Effects]/img/fx2/headlight1.png",
    "headlight1"
  },
  {
    "[Realistic-Effects]/img/fx2/lamp_shad_64.png",
    "lamp_shad_64"
  },
  {
    "[Realistic-Effects]/img/fx2/lockon.png",
    "lockon"
  },
  {
    "[Realistic-Effects]/img/fx2/lockonFire.png",
    "lockonFire"
  },
  {
    "[Realistic-Effects]/img/fx2/lunar.png",
    "lunar"
  },
  {
    "[Realistic-Effects]/img/fx2/particleskid.png",
    "particleskid"
  },
  {
    "[Realistic-Effects]/img/fx2/rainfx.png",
    "rainfx"
  },
  {
    "[Realistic-Effects]/img/fx2/roadsignfont.png",
    "roadsignfont"
  },
  {
    "[Realistic-Effects]/img/fx2/seabd32.png",
    "seabd32"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_bike.png",
    "shad_bike"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_car.png",
    "shad_car"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_exp.png",
    "shad_exp"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_heli.png",
    "shad_heli"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_ped.png",
    "shad_ped"
  },
  {
    "[Realistic-Effects]/img/fx2/shad_rcbaron.png",
    "shad_rcbaron"
  },
  {
    "[Realistic-Effects]/img/fx2/Sky.png",
    "Sky"
  },
  {
    "[Realistic-Effects]/img/fx2/Sky2.png",
    "Sky2"
  },
  {
    "[Realistic-Effects]/img/fx2/Sky3.png",
    "Sky3"
  },
  {
    "[Realistic-Effects]/img/fx2/Skysnow.png",
    "Skysnow"
  },
  {
    "[Realistic-Effects]/img/fx2/target256.png",
    "target256"
  },
  {
    "[Realistic-Effects]/img/fx2/txgrassbig0.png",
    "txgrassbig0"
  },
  {
    "[Realistic-Effects]/img/fx2/txgrassbig1.png",
    "txgrassbig1"
  },
  {
    "[Realistic-Effects]/img/fx2/waterwake.png",
    "waterwake"
  },
  {
    "[Realistic-Effects]/img/fx2/white.png",
    "white"
  },
  {
    "[Realistic-Effects]/img/fx2/wincrack_32.png",
    "wincrack_32"
  }
}

local row = {}

function switchEfectosR( bool )
  outputDebugString( "switchEfectosR: " .. tostring(bool) )
  if bool then
    aplicarEfectos()
  else
    removerEfectos()
  end
end


function aplicarEfectos()
  for i = 1, #texturesimg do
    texturesEffects = dxCreateTexture(texturesimg[i][1])
    row[i] = dxCreateShader("[Realistic-Effects]/shader/shader.fx")
    dxSetShaderValue(row[i], "gTexture", texturesEffects)
    engineApplyShaderToWorldTexture(row[i], texturesimg[i][2])
  end
end

function removerEfectos()
  for i = 1, #texturesimg do
    engineRemoveShaderFromWorldTexture ( row[i], texturesimg[i][2] ) 
  end
  if isElement( row[i] ) then
    destroyElement( row[i] )
  end
  if isElement( texturesEffects ) then
    destroyElement( texturesEffects )
  end
end
